server:
  port: 8085

spring:
  application:
    name: score-service

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/student_score.db

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.common.entity
  global-config:
    db-config:
      id-type: none
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '成绩服务'
      paths-to-match: '/**'
      packages-to-scan: com.example.score.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com.example.score: debug
