server:
  port: 8087

spring:
  application:
    name: file-service
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/student_score.db

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.common.entity
  global-config:
    db-config:
      id-type: none
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '文件服务'
      paths-to-match: '/**'
      packages-to-scan: com.example.file.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

# 文件上传路径
file:
  upload-path: ../uploads/

logging:
  level:
    com.example.file: debug
